# Generated by Django 4.1.4 on 2022-12-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Erkaklar'), ('W', 'Atollar'), ('Ch', 'Bolalar')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
